apiVersion: v1
kind: ServiceAccount
metadata:
  name: nept-analytics-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nept-analytics-role
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nept-analytics-rolebinding
subjects:
  - kind: ServiceAccount
    name: nept-analytics-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: nept-analytics-role
  apiGroup: rbac.authorization.k8s.io
